<#
.SYNOPSIS
  DCR Intent Log Aggregator
  .dcr/intent-log.jsonl を読み込み、ルーティング精度統計と重み調整提案を出力する

.DESCRIPTION
  出力:
    1. スキル/ルール別の選択頻度
    2. 成功率（outcome = success の割合）
    3. オーバーライド率（ユーザーが選択を上書きした割合）
    4. カテゴリ別の初回正答率
    5. 重み調整提案（サンプル数 >= 5 のもの）

.PARAMETER LogPath
  intent-log.jsonl のパス（デフォルト: .dcr/intent-log.jsonl）

.PARAMETER OutputPath
  集計結果の出力先（デフォルト: .dcr/intent-weights.md）

.EXAMPLE
  .\tools\aggregate-intent.ps1
  .\tools\aggregate-intent.ps1 -LogPath .dcr/intent-log.jsonl
#>

param(
    [string]$LogPath,
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot

if (-not $LogPath) {
    $LogPath = Join-Path $RepoRoot ".dcr\intent-log.jsonl"
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $RepoRoot ".dcr\intent-weights.md"
}

if (-not (Test-Path $LogPath)) {
    Write-Host "No intent log found at: $LogPath" -ForegroundColor Yellow
    Write-Host "Intent logging has not started yet. The skill-router will create entries as routing decisions are made." -ForegroundColor DarkGray
    exit 0
}

# Read all records
$records = @()
foreach ($line in (Get-Content -Path $LogPath -Encoding utf8)) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
    try {
        $record = $trimmed | ConvertFrom-Json
        $records += $record
    } catch {
        Write-Warning "Skipping invalid line: $trimmed"
    }
}

if ($records.Count -eq 0) {
    Write-Host "Intent log is empty." -ForegroundColor Yellow
    exit 0
}

Write-Host "Processing $($records.Count) intent records..." -ForegroundColor Cyan

# 1. Frequency table
$frequency = @{}
foreach ($r in $records) {
    $sel = $r.selected
    if (-not $sel) { continue }
    if (-not $frequency.ContainsKey($sel)) { $frequency[$sel] = 0 }
    $frequency[$sel]++
}

# 2. Success rate
$successCounts = @{}
$totalCounts = @{}
foreach ($r in $records) {
    $sel = $r.selected
    if (-not $sel) { continue }
    if (-not $totalCounts.ContainsKey($sel)) { $totalCounts[$sel] = 0; $successCounts[$sel] = 0 }
    if ($r.outcome) {
        $totalCounts[$sel]++
        if ($r.outcome -eq 'success') { $successCounts[$sel]++ }
    }
}

# 3. Override rate
$overrideCounts = @{}
foreach ($r in $records) {
    $sel = $r.selected
    if (-not $sel) { continue }
    if (-not $overrideCounts.ContainsKey($sel)) { $overrideCounts[$sel] = 0 }
    if ($r.override) { $overrideCounts[$sel]++ }
}

# 4. Category accuracy
$categoryTotal = @{}
$categoryCorrect = @{}
foreach ($r in $records) {
    $cat = $r.category
    if (-not $cat) { continue }
    if (-not $categoryTotal.ContainsKey($cat)) { $categoryTotal[$cat] = 0; $categoryCorrect[$cat] = 0 }
    $categoryTotal[$cat]++
    if ($r.outcome -eq 'success' -and -not $r.override) {
        $categoryCorrect[$cat]++
    }
}

# 5. Weight suggestions
$weights = @{}
foreach ($sel in $frequency.Keys) {
    $total = if ($totalCounts.ContainsKey($sel)) { $totalCounts[$sel] } else { 0 }
    if ($total -lt 5) { continue }

    $successRate = $successCounts[$sel] / $total
    $overrideRate = if ($frequency[$sel] -gt 0) { $overrideCounts[$sel] / $frequency[$sel] } else { 0 }

    $adj = [math]::Round(($successRate - 0.5) * 4 - $overrideRate * 3)
    if ($adj -lt -3) { $adj = -3 }
    if ($adj -gt 3) { $adj = 3 }

    $weights[$sel] = @{
        adjustment = $adj
        success_rate = [math]::Round($successRate, 2)
        override_rate = [math]::Round($overrideRate, 2)
        sample = $total
    }
}

# Generate output
$lines = @()
$lines += "# DCR Intent-Based Weight Adjustments"
$lines += ""
$lines += "Auto-generated by ``tools/aggregate-intent.ps1``."
$lines += "Records processed: $($records.Count)"
$lines += ""

$lines += "## Frequency"
$lines += ""
$lines += "| Skill/Rule | Count |"
$lines += "|---|---|"
foreach ($entry in ($frequency.GetEnumerator() | Sort-Object Value -Descending)) {
    $lines += "| $($entry.Key) | $($entry.Value) |"
}

$lines += ""
$lines += "## Category Accuracy"
$lines += ""
$lines += "| Category | Correct | Total | Rate |"
$lines += "|---|---|---|---|"
foreach ($cat in ($categoryTotal.Keys | Sort-Object)) {
    $correct = if ($categoryCorrect.ContainsKey($cat)) { $categoryCorrect[$cat] } else { 0 }
    $total = $categoryTotal[$cat]
    $rate = if ($total -gt 0) { [math]::Round($correct / $total * 100) } else { 0 }
    $lines += "| $cat | $correct | $total | ${rate}% |"
}

$lines += ""
$lines += "## Weight Adjustments (sample >= 5)"
$lines += ""
if ($weights.Count -eq 0) {
    $lines += "No skills have enough samples yet (minimum 5 decisions with outcome)."
} else {
    $lines += "| Skill/Rule | Adjustment | Success | Override | Samples |"
    $lines += "|---|---|---|---|---|"
    foreach ($entry in ($weights.GetEnumerator() | Sort-Object { $_.Value.adjustment } -Descending)) {
        $w = $entry.Value
        $sign = if ($w.adjustment -ge 0) { "+$($w.adjustment)" } else { "$($w.adjustment)" }
        $lines += "| $($entry.Key) | $sign | $($w.success_rate) | $($w.override_rate) | $($w.sample) |"
    }
}

$lines += ""

$content = $lines -join "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $content, $utf8NoBom)

Write-Host "Intent weight report: $OutputPath" -ForegroundColor Green
Write-Host "  Total records: $($records.Count)" -ForegroundColor DarkGray
Write-Host "  Skills with weight adjustment: $($weights.Count)" -ForegroundColor DarkGray
