param(
    [string]$RepoRoot = $PSScriptRoot + "\\..",
    [string]$OutputPath = "",
    [string]$SkillsOutputPath = ""
)

$ErrorActionPreference = "Stop"

$resolvedRoot = (Resolve-Path $RepoRoot).Path
$CatalogPaths = Join-Path $resolvedRoot "tools\lib\catalog-paths.ps1"
. $CatalogPaths
$rulesDir = Resolve-DcrSourcePath -RepoRoot $resolvedRoot -AssetType "rules"
if (-not (Test-Path $rulesDir)) {
    throw "rules directory not found: $rulesDir"
}

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $rulesDir "_ROUTING_INDEX.md"
}

function Get-FrontmatterMap {
    param([string]$FilePath)

    $raw = Get-Content -Path $FilePath -Raw -Encoding utf8
    if (-not $raw.StartsWith("---")) {
        return $null
    }

    $m = [regex]::Match($raw, '(?s)^---\r?\n(.*?)\r?\n---')
    if (-not $m.Success) {
        return $null
    }

    $lines = $m.Groups[1].Value -split "`r?`n"
    $map = @{}
    $i = 0
    while ($i -lt $lines.Count) {
        $line = $lines[$i]
        # Top-level YAML keys only (no leading whitespace)
        if ($line -notmatch '^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$') {
            $i++
            continue
        }

        $key = $Matches[1]
        $rest = $Matches[2].TrimEnd()

        # YAML literal block scalar: key: | / |- / |+
        if ($rest -match '^\|([-+]?)?$') {
            $i++
            $blockParts = [System.Collections.Generic.List[string]]::new()
            while ($i -lt $lines.Count) {
                $next = $lines[$i]
                if ($next -match '^[a-zA-Z_][a-zA-Z0-9_-]*\s*:') {
                    break
                }
                if (-not [string]::IsNullOrWhiteSpace($next)) {
                    $stripped = ($next -replace '^\s+', '').TrimEnd()
                    if (-not [string]::IsNullOrWhiteSpace($stripped)) {
                        $blockParts.Add($stripped)
                    }
                }
                $i++
            }
            $joined = ($blockParts -join " ").Trim()
            if (-not [string]::IsNullOrWhiteSpace($joined)) {
                $map[$key] = $joined
            }
            continue
        }

        $value = $rest.Trim().Trim('"').Trim("'")
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            $map[$key] = $value
        }
        $i++
    }

    return $map
}

$rows = @()
$files = Get-ChildItem -Path $rulesDir -File -Filter *.md |
    Where-Object { $_.BaseName -ne "README" -and $_.BaseName -notlike "_*" } |
    Sort-Object Name

foreach ($file in $files) {
    $fm = Get-FrontmatterMap -FilePath $file.FullName
    if ($null -eq $fm) {
        continue
    }

    $category = ""
    $domain = ""
    $risk = ""
    $description = ""
    if ($fm.ContainsKey("routing_category")) { $category = $fm["routing_category"] }
    if ($fm.ContainsKey("domain")) { $domain = $fm["domain"] }
    if ($fm.ContainsKey("risk")) { $risk = $fm["risk"] }
    if ($fm.ContainsKey("description")) { $description = $fm["description"] }

    $rows += [pscustomobject]@{
        File = $file.Name
        Category = $category
        Domain = $domain
        Risk = $risk
        Description = $description
    }
}

$lines = @()
$lines += "# Routing Index"
$lines += ""
$lines += "This file is generated by tools/generate-routing-index.ps1. Do not edit manually."
$lines += ""
$lines += "| File | routing_category | domain | risk | description |"
$lines += "|---|---|---|---|---|"

foreach ($row in $rows) {
    $desc = $row.Description.Replace("|", "\\|")
    $lines += "| $($row.File) | $($row.Category) | $($row.Domain) | $($row.Risk) | $desc |"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, ($lines -join "`n") + "`n", $utf8NoBom)

Write-Host "Generated routing index:" -ForegroundColor Green
Write-Host "  $OutputPath"
Write-Host "  entries: $($rows.Count)"

# ── Skills Routing Index (optional) ──────────────────────────────────────────
if (-not [string]::IsNullOrWhiteSpace($SkillsOutputPath)) {
    $skillsDir = Resolve-DcrSourcePath -RepoRoot $resolvedRoot -AssetType "skills"
    if (-not (Test-Path $skillsDir)) {
        Write-Warning "skills directory not found: $skillsDir — skipping skills index"
    } else {
        $skillRows = @()
        $skillDirs = Get-ChildItem -Path $skillsDir -Directory |
            Where-Object { $_.Name -notlike "_*" } |
            Sort-Object Name

        foreach ($dir in $skillDirs) {
            $sf = Join-Path $dir.FullName "SKILL.md"
            if (-not (Test-Path $sf)) { continue }

            $fm = Get-FrontmatterMap -FilePath $sf
            if ($null -eq $fm) { continue }

            # Skip deprecated skills
            if ($fm.ContainsKey("deprecated") -and $fm["deprecated"] -eq "true") { continue }

            $skillCategory = ""
            $skillDesc = ""
            if ($fm.ContainsKey("routing_category")) { $skillCategory = $fm["routing_category"] }
            if ($fm.ContainsKey("description")) { $skillDesc = $fm["description"] }

            $skillRows += [pscustomobject]@{
                Skill       = $dir.Name
                Category    = $skillCategory
                Description = $skillDesc
            }
        }

        $skillLines = @()
        $skillLines += "# Skills Routing Index"
        $skillLines += ""
        $skillLines += "This file is generated by tools/generate-routing-index.ps1. Do not edit manually."
        $skillLines += ""
        $skillLines += "| Skill | routing_category | description |"
        $skillLines += "|---|---|---|"

        foreach ($row in $skillRows) {
            $desc = $row.Description.Replace("|", "\|")
            $skillLines += "| $($row.Skill) | $($row.Category) | $desc |"
        }

        [System.IO.File]::WriteAllText($SkillsOutputPath, ($skillLines -join "`n") + "`n", $utf8NoBom)

        Write-Host "Generated skills routing index:" -ForegroundColor Green
        Write-Host "  $SkillsOutputPath"
        Write-Host "  entries: $($skillRows.Count)"
    }
}
