param(
    [string]$RepoRoot = $PSScriptRoot + "\\..",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$resolvedRoot = (Resolve-Path $RepoRoot).Path
$CatalogPaths = Join-Path $resolvedRoot "tools\lib\catalog-paths.ps1"
. $CatalogPaths
$rulesDir = Resolve-DcrSourcePath -RepoRoot $resolvedRoot -AssetType "rules"
if (-not (Test-Path $rulesDir)) {
    throw "rules directory not found: $rulesDir"
}

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $rulesDir "_ROUTING_INDEX.md"
}

function Get-FrontmatterMap {
    param([string]$FilePath)

    $raw = Get-Content -Path $FilePath -Raw -Encoding utf8
    if (-not $raw.StartsWith("---")) {
        return $null
    }

    $m = [regex]::Match($raw, '(?s)^---\r?\n(.*?)\r?\n---')
    if (-not $m.Success) {
        return $null
    }

    $map = @{}
    foreach ($line in ($m.Groups[1].Value -split "`r?`n")) {
        if ($line -match '^\s*([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$') {
            $key = $Matches[1]
            $value = $Matches[2].Trim().Trim('"').Trim("'")
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                $map[$key] = $value
            }
        }
    }

    return $map
}

$rows = @()
$files = Get-ChildItem -Path $rulesDir -File -Filter *.md |
    Where-Object { $_.BaseName -notlike "_*" } |
    Sort-Object Name

foreach ($file in $files) {
    $fm = Get-FrontmatterMap -FilePath $file.FullName
    if ($null -eq $fm) {
        continue
    }

    $category = ""
    $domain = ""
    $risk = ""
    $description = ""
    if ($fm.ContainsKey("routing_category")) { $category = $fm["routing_category"] }
    if ($fm.ContainsKey("domain")) { $domain = $fm["domain"] }
    if ($fm.ContainsKey("risk")) { $risk = $fm["risk"] }
    if ($fm.ContainsKey("description")) { $description = $fm["description"] }

    $rows += [pscustomobject]@{
        File = $file.Name
        Category = $category
        Domain = $domain
        Risk = $risk
        Description = $description
    }
}

$lines = @()
$lines += "# Routing Index"
$lines += ""
$lines += "This file is generated by tools/generate-routing-index.ps1. Do not edit manually."
$lines += ""
$lines += "| File | routing_category | domain | risk | description |"
$lines += "|---|---|---|---|---|"

foreach ($row in $rows) {
    $desc = $row.Description.Replace("|", "\\|")
    $lines += "| $($row.File) | $($row.Category) | $($row.Domain) | $($row.Risk) | $desc |"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, ($lines -join "`n") + "`n", $utf8NoBom)

Write-Host "Generated routing index:" -ForegroundColor Green
Write-Host "  $OutputPath"
Write-Host "  entries: $($rows.Count)"
